version: "3.8"
services:
    www:
        build: .
        container_name: 'pw-ap2_www'
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www/html/
        networks:
            - default
    db:
        image: mysql:8.0
        container_name: 'pw-ap2_mysql'
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
          - ./database/mysql:/var/lib/mysql
          - ./database/logs:/var/log/mysql
          - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: 'pw-ap2_phpmyadmin'
        ports:
            - 8080:80
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            - default
networks:
    default:
        driver: bridge
